'use strict';
//
// Migration routes (Settings → Migration).
//
//   POST   /system/api/migration/token    receiver: generate a single-use accept code (admin)
//   GET    /system/api/migration/token     receiver: is a code currently active? (admin)
//   DELETE /system/api/migration/token     receiver: cancel the active code (admin)
//   POST   /system/api/migration/send      sender: encrypt local config, push to a receiver (admin)
//   POST   /migration/receive              receiver: accept an encrypted push (authed by the code itself)
//
// The admin endpoints sit behind the admin session (never the API key), like
// software updates. /migration/receive is deliberately public — the sender is a
// different server and only has the accept code — but the code is the AES-GCM
// key, so an invalid code can neither decrypt nor forge a payload.
//
const express = require('express');
const http = require('http');
const https = require('https');
const { URL } = require('url');
const logger = require('../utils/logger');
const migration = require('../services/migration');

function createMigrationRouter({ models }) {
  const router = express.Router();
  const web = require('./web');
  const admin = [web.authMiddleware, web.adminOnly];

  // ── Receiver: accept code lifecycle ──
  router.post('/system/api/migration/token', ...admin, (req, res) => {
    const t = migration.newToken();
    logger.info(`MIGRATION: accept code generated by ${req.session ? req.session.user : 'admin'} (expires ${new Date(t.expiresAt).toISOString()})`);
    res.json({ success: true, token: t.token, expiresAt: t.expiresAt, ttlMin: Math.round((t.expiresAt - t.createdAt) / 60000) });
  });
  router.get('/system/api/migration/token', ...admin, (req, res) => {
    res.json({ success: true, active: migration.tokenStatus() });
  });
  router.delete('/system/api/migration/token', ...admin, (req, res) => {
    migration.cancelToken();
    res.json({ success: true });
  });

  // ── Sender: push local config to a receiver ──
  router.post('/system/api/migration/send', ...admin, async (req, res) => {
    try {
      const target = String((req.body && req.body.target) || '').trim();
      const token = String((req.body && req.body.token) || '').trim();
      if (!target || !token) return res.status(400).json({ success: false, error: 'Receiver address and accept code are required' });
      const cfg = await migration.exportConfig(models);
      const payload = migration.encrypt(cfg, token);
      const result = await postReceive(target, payload);
      logger.info(`MIGRATION: sent ${cfg.total} config items to ${target} by ${req.session ? req.session.user : 'admin'}`);
      res.json({ success: true, sent: cfg.total, result });
    } catch (err) {
      logger.error(`MIGRATION send failed: ${err.message}`);
      res.status(400).json({ success: false, error: err.message });
    }
  });

  // ── Receiver: accept an encrypted push. Auth = the accept code (decryption). ──
  router.post('/migration/receive', express.json({ limit: '10mb' }), async (req, res) => {
    const src = req.ip || (req.connection && req.connection.remoteAddress) || '?';
    const token = migration.currentToken();
    if (!token) {
      logger.warn(`MIGRATION: receive from ${src} rejected — no active accept code`);
      return res.status(403).json({ success: false, error: 'No active accept code on this server' });
    }
    const payload = req.body && req.body.payload;
    if (!payload) return res.status(400).json({ success: false, error: 'Missing payload' });
    let cfg;
    try {
      cfg = migration.decrypt(payload, token);
    } catch (e) {
      logger.warn(`MIGRATION: receive from ${src} rejected — decrypt/auth failed (wrong code or corrupt payload)`);
      return res.status(401).json({ success: false, error: 'Invalid accept code or corrupt payload' });
    }
    // Decryption with the active code succeeded → burn it (single use).
    if (!migration.consumeToken(token)) {
      return res.status(409).json({ success: false, error: 'Accept code already used or expired' });
    }
    try {
      const backup = await migration.snapshot(models);      // rollback file first
      const applied = await migration.applyConfig(models, cfg);
      migration.markUsed();
      migration.cancelToken();
      logger.info(`MIGRATION: applied config from ${src} (rollback snapshot: ${backup})`);
      res.json({ success: true, applied, backup });
    } catch (err) {
      logger.error(`MIGRATION apply failed from ${src}: ${err.message}`);
      res.status(500).json({ success: false, error: err.message });
    }
  });

  // ── Rollback: list snapshots and restore one (admin) ──
  router.get('/system/api/migration/snapshots', ...admin, (req, res) => {
    res.json({ success: true, snapshots: migration.listSnapshots() });
  });
  router.post('/system/api/migration/restore', ...admin, async (req, res) => {
    try {
      const file = String((req.body && req.body.file) || '').trim();
      if (!file) return res.status(400).json({ success: false, error: 'snapshot file is required' });
      const applied = await migration.restoreSnapshot(models, file);
      logger.info(`MIGRATION: restored snapshot ${file} by ${req.session ? req.session.user : 'admin'}`);
      res.json({ success: true, restored: applied });
    } catch (err) {
      res.status(400).json({ success: false, error: err.message });
    }
  });

  return router;
}

// POST the encrypted payload to <target>/migration/receive via native http(s).
function postReceive(target, payload) {
  return new Promise((resolve, reject) => {
    let base = String(target).trim();
    if (!/^https?:\/\//i.test(base)) base = 'http://' + base; // default scheme
    let u;
    try { u = new URL(base); } catch (e) { return reject(new Error('Invalid receiver address')); }
    const isHttps = u.protocol === 'https:';
    const port = u.port || (isHttps ? '443' : '3000'); // default to the app port on plain http
    const body = JSON.stringify({ payload });
    const lib = isHttps ? https : http;
    const opts = {
      method: 'POST', hostname: u.hostname, port,
      path: '/migration/receive',
      headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body) },
      timeout: 30000,
    };
    const rq = lib.request(opts, (rs) => {
      let d = '';
      rs.on('data', (c) => { d += c; });
      rs.on('end', () => {
        let j;
        try { j = JSON.parse(d); } catch (e) { return reject(new Error(`Receiver returned ${rs.statusCode}`)); }
        if (!j.success) return reject(new Error(j.error || `Receiver error ${rs.statusCode}`));
        resolve(j);
      });
    });
    rq.on('timeout', () => rq.destroy(new Error('Receiver timed out')));
    rq.on('error', reject);
    rq.write(body);
    rq.end();
  });
}

module.exports = { createMigrationRouter };
